/**
 * AI Insights Service
 * Analyzes HR Connect survey remarks and generates positive/negative insights
 */

interface DetailedInsight {
  summary: string;
  explanation: string;
}

interface InsightResult {
  positives: string[];
  negatives: string[];
  isAiGenerated: boolean; // Indicates if insights were generated by AI or fallback analysis
  detailedInsights?: {
    positives: DetailedInsight[];
    negatives: DetailedInsight[];
  };
}

/**
 * Analyzes submission remarks using AI to generate insights
 * @param submissions - Array of submissions to analyze
 * @returns Promise with positive and negative insights
 */
export async function generateAMInsights(submissions: any[]): Promise<InsightResult> {
  try {
    // Collect all remarks from submissions
    const remarks: string[] = [];
    
    submissions.forEach((sub: any) => {
      // Collect question remarks (q1_remarks through q12_remarks)
      for (let i = 1; i <= 12; i++) {
        const remarkKey = `q${i}_remarks`;
        const remark = sub[remarkKey];
        if (remark && String(remark).trim().length > 5) {
          remarks.push(String(remark).trim());
        }
      }
      
      // Also check for q11 (suggestions) which is a textarea
      if (sub.q11 && String(sub.q11).trim().length > 5) {
        remarks.push(String(sub.q11).trim());
      }
    });

    // If no remarks found, return default insights
    if (remarks.length === 0) {
      const defaultDetailedPositives = [
        { summary: 'Team performance is steady', explanation: 'The team maintains consistent work quality and meets basic job requirements. Staff complete their daily tasks reliably and serve customers properly.' },
        { summary: 'Staff seem engaged at work', explanation: 'Employees appear to be interested in their work and participate in daily activities. There are no major signs of disengagement or unhappiness.' },
        { summary: 'Work standards are being followed', explanation: 'Staff follow the company procedures and maintain the expected level of service quality. Basic operational requirements are being met consistently.' }
      ];
      
      const defaultDetailedNegatives = [
        { summary: 'Staff are not giving much feedback', explanation: 'Employees are not sharing their thoughts or suggestions about how to improve the workplace. This makes it harder to identify and solve problems.' },
        { summary: 'Need more detailed opinions from staff', explanation: 'The feedback received is too general or brief. More specific input from employees would help understand what is working well and what needs improvement.' },
        { summary: 'Communication could be better', explanation: 'There may be gaps in communication between staff and management. Better channels for sharing information and feedback would help everyone understand expectations and concerns.' }
      ];
      
      return {
        positives: defaultDetailedPositives.map(d => d.summary),
        negatives: defaultDetailedNegatives.map(d => d.summary),
        isAiGenerated: false,
        detailedInsights: {
          positives: defaultDetailedPositives,
          negatives: defaultDetailedNegatives
        }
      };
    }

    // Use GitHub Models API (or fallback to local analysis)
    const insights = await analyzeWithAI(remarks, submissions);
    return insights;
    
  } catch (error) {
    console.error('Error generating AI insights:', error);
    // Return fallback insights
    return generateFallbackInsights(submissions);
  }
}

/**
 * Analyzes remarks using AI (GitHub Models or local analysis)
 */
async function analyzeWithAI(remarks: string[], submissions: any[]): Promise<InsightResult> {
  // GitHub token should be set via environment variable GITHUB_TOKEN
  const githubToken = process.env.GITHUB_TOKEN || ''; // Set your GitHub Personal Access Token in environment variables
  
  if (githubToken && githubToken.length > 0) {
    try {
      return await analyzeWithGitHubModels(remarks, submissions, githubToken);
    } catch (error) {
      console.warn('GitHub Models API failed, using fallback analysis:', error);
    }
  }
  
  // Fallback to local analysis
  return generateFallbackInsights(submissions);
}

/**
 * Uses GitHub Models API to analyze remarks
 */
async function analyzeWithGitHubModels(
  remarks: string[], 
  submissions: any[], 
  token: string
): Promise<InsightResult> {
  const endpoint = 'https://models.github.ai/inference/chat/completions';
  
  // Collect detailed response data for root cause analysis
  const responseData: { [key: string]: { scores: number[], remarks: string[] } } = {};
  
  submissions.forEach(sub => {
    for (let i = 1; i <= 12; i++) {
      const qKey = `q${i}`;
      const remarkKey = `${qKey}_remarks`;
      
      if (!responseData[qKey]) {
        responseData[qKey] = { scores: [], remarks: [] };
      }
      
      const score = parseScore(sub[qKey]);
      if (score > 0) {
        responseData[qKey].scores.push(score);
      }
      
      const remark = sub[remarkKey];
      if (remark && String(remark).trim().length > 5) {
        responseData[qKey].remarks.push(String(remark).trim());
      }
    }
    
    // Q11 suggestions
    if (sub.q11 && String(sub.q11).trim().length > 5) {
      if (!responseData['q11']) responseData['q11'] = { scores: [], remarks: [] };
      responseData['q11'].remarks.push(String(sub.q11).trim());
    }
  });
  
  // Calculate averages and prepare detailed analysis data
  const questionAnalysis = Object.entries(responseData).map(([q, data]) => {
    const avg = data.scores.length > 0 
      ? (data.scores.reduce((a, b) => a + b, 0) / data.scores.length).toFixed(1)
      : 'N/A';
    return {
      question: q,
      avgScore: avg,
      remarkCount: data.remarks.length,
      sampleRemarks: data.remarks.slice(0, 3)
    };
  }).filter(q => q.remarkCount > 0 || q.avgScore !== 'N/A');
  
  // Question context with reverse scoring info
  const questionContext = `
Question Details (1-5 scale where 5 is best, unless noted):
Q1: Work pressure (REVERSE: 5=never pressured, 1=always pressured)
Q2: Empowerment in customer decisions
Q3: Regular feedback from manager
Q4: Fair treatment (REVERSE: 5=always fair, 1=never fair)
Q5: Wings training program quality
Q6: Apps/benefits issues (REVERSE: 5=no issues, 1=many issues)
Q7: HR handbook awareness
Q8: Work schedule satisfaction
Q9: Team collaboration quality
Q10: Helpful colleague (text response)
Q11: Improvement suggestions (text response)
Q12: Overall TWC experience
`;
  
  // Prepare root cause analysis prompt
  const prompt = `Perform DETAILED ROOT CAUSE ANALYSIS on employee survey data to identify SPECIFIC underlying factors.

${questionContext}

Question-wise Analysis:
${questionAnalysis.map(q => `
${q.question}: Avg Score ${q.avgScore}/5 (${q.remarkCount} remarks)
Sample remarks: ${q.sampleRemarks.map(r => `"${r}"`).join(', ')}
`).join('\n')}

ANALYSIS REQUIREMENTS:
1. Identify SPECIFIC operational, managerial, or systemic root causes
2. Connect score patterns to underlying business factors
3. Look for correlations between related questions (e.g., Q1+Q8 = workload management)
4. Extract actionable insights from employee language patterns
5. Focus on CONCRETE causes, NOT vague descriptions

ROOT CAUSE CATEGORIES to consider:
- Staffing levels & workload distribution
- Management communication & feedback frequency  
- System/technology reliability & functionality
- Training program design & delivery methods
- Policy clarity & implementation consistency
- Work schedule flexibility & break management
- Team dynamics & collaboration processes

For POSITIVES: Identify what management/operational practices are working well
For NEGATIVES: Identify what specific processes/systems need improvement

AVOID generic terms like "poor content", "bad management", "issues"
USE specific terms like "understaffing during peak hours", "infrequent manager check-ins", "app crashes during transactions"

Format: "[Main Issue]: [Simple explanation]" (max 120 chars for better detail)

Examples:
✓ "Good staffing levels: We have enough people working during busy times so nobody feels too much pressure"  
✓ "Manager talks regularly: Area manager meets with staff every week to give feedback and help solve problems"
✓ "App keeps crashing: The computer system stops working often which makes it hard to serve customers quickly"
✗ "Poor content" or "Bad management" or "Issues exist"

Use SIMPLE, CLEAR language that anyone can understand.

Return ONLY valid JSON with both short summaries AND detailed explanations:
{
  "positives": [
    {
      "summary": "Short title for the positive thing",
      "explanation": "Detailed explanation in simple English about why this is good and what causes it to work well"
    },
    {
      "summary": "Short title for the positive thing", 
      "explanation": "Detailed explanation in simple English about why this is good and what causes it to work well"
    },
    {
      "summary": "Short title for the positive thing",
      "explanation": "Detailed explanation in simple English about why this is good and what causes it to work well"
    }
  ],
  "negatives": [
    {
      "summary": "Short title for the problem",
      "explanation": "Detailed explanation in simple English about what causes this problem and why it happens"
    },
    {
      "summary": "Short title for the problem",
      "explanation": "Detailed explanation in simple English about what causes this problem and why it happens"  
    },
    {
      "summary": "Short title for the problem",
      "explanation": "Detailed explanation in simple English about what causes this problem and why it happens"
    }
  ]
}`;

  const response = await fetch(endpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${token}`
    },
    body: JSON.stringify({
      model: 'gpt-4.1-mini',
      messages: [
        {
          role: 'system',
          content: 'You are an expert workplace analyst who explains things in SIMPLE, CLEAR language that anyone can understand. You identify specific reasons why things are working well or poorly at work. Use everyday words, not technical jargon. Write as if explaining to someone who is new to the company. NEVER use vague terms like "poor content" or "bad management". Instead, explain exactly what is happening - like "not enough people working during busy times" or "manager only talks to staff once per month". Your explanations should be detailed but easy to read. Always respond with valid JSON only.'
        },
        {
          role: 'user',
          content: prompt
        }
      ],
      temperature: 0.3,
      max_tokens: 500
    })
  });

  if (!response.ok) {
    const errorText = await response.text();
    console.error('GitHub Models API error:', response.status, errorText);
    throw new Error(`GitHub Models API error: ${response.status}`);
  }

  const data = await response.json();
  const content = data.choices?.[0]?.message?.content || '';
  
  console.log('AI Root Cause Analysis:', content);
  
  // Parse JSON from response
  const jsonMatch = content.match(/\{[\s\S]*\}/);
  if (jsonMatch) {
    try {
      const parsed = JSON.parse(jsonMatch[0]);
      
      // Convert new format to existing format for compatibility
      const positives = (parsed.positives || []).slice(0, 3).map((item: any) => {
        if (typeof item === 'string') return item;
        return `${item.summary}: ${item.explanation}`;
      });
      
      const negatives = (parsed.negatives || []).slice(0, 3).map((item: any) => {
        if (typeof item === 'string') return item;
        return `${item.summary}: ${item.explanation}`;
      });
      
      return {
        positives,
        negatives,
        isAiGenerated: true,
        detailedInsights: {
          positives: (parsed.positives || []).slice(0, 3),
          negatives: (parsed.negatives || []).slice(0, 3)
        }
      };
    } catch (e) {
      console.error('Failed to parse AI JSON:', e);
    }
  }
  
  throw new Error('Could not parse AI response');
}

/**
 * Generates insights using local analysis when AI is not available
 */
function generateFallbackInsights(submissions: any[]): InsightResult {
  const positives: Map<string, number> = new Map();
  const negatives: Map<string, number> = new Map();
  
  // Collect all remarks for frequency analysis
  const allRemarks: string[] = [];
  const scoresByQuestion: { [key: string]: number[] } = {};
  
  submissions.forEach((sub: any) => {
    // Collect remarks
    for (let i = 1; i <= 12; i++) {
      const remarkKey = `q${i}_remarks`;
      const remark = sub[remarkKey];
      if (remark && String(remark).trim().length > 5) {
        allRemarks.push(String(remark).trim().toLowerCase());
      }
      
      // Collect scores
      const scoreKey = `q${i}`;
      const score = parseScore(sub[scoreKey]);
      if (score > 0) {
        if (!scoresByQuestion[scoreKey]) {
          scoresByQuestion[scoreKey] = [];
        }
        scoresByQuestion[scoreKey].push(score);
      }
    }
    
    // Also collect q11 (suggestions)
    if (sub.q11 && String(sub.q11).trim().length > 5) {
      allRemarks.push(String(sub.q11).trim().toLowerCase());
    }
  });

  // Analyze remarks for keywords with detailed root cause themes in simple English
  const positiveKeywords = [
    { 
      words: ['good', 'great', 'excellent', 'satisfied', 'happy'], 
      theme: 'Team is doing well',
      explanation: 'Staff feel happy and satisfied because they are getting good support and the work environment is positive. This happens when managers care about their team and help them succeed.'
    },
    { 
      words: ['support', 'help', 'care', 'understanding', 'friendly'], 
      theme: 'Manager gives good help',
      explanation: 'The area manager is supportive and helps staff when they need it. This makes people feel valued and confident at work. Good managers check on their team regularly and solve problems quickly.'
    },
    { 
      words: ['fair', 'equal', 'respect', 'dignity', 'unbiased'], 
      theme: 'Everyone gets treated fairly',
      explanation: 'All staff members are treated the same way and with respect. This happens when managers follow company rules properly and do not show favoritism to certain people.'
    },
    { 
      words: ['training', 'learn', 'develop', 'skill', 'knowledge'], 
      theme: 'Good training programs',
      explanation: 'Staff are getting proper training that helps them do their job better. This works well when training is clear, practical, and gives people the skills they actually need for their daily work.'
    },
    { 
      words: ['balance', 'flexible', 'schedule', 'time'], 
      theme: 'Good work schedules',
      explanation: 'Work schedules are flexible and allow people to balance their job with personal life. This happens when managers plan shifts properly and consider staff needs when making rosters.'
    },
    { 
      words: ['communication', 'feedback', 'listen', 'talk'], 
      theme: 'Manager talks with staff regularly',
      explanation: 'The area manager communicates well and listens to staff concerns. This creates trust because people know their manager cares about their opinions and will help solve problems.'
    },
    { 
      words: ['team', 'colleague', 'together', 'cooperation'], 
      theme: 'Team works well together',
      explanation: 'Staff members help each other and work as a team. This happens when there is good leadership and everyone understands their role. People feel comfortable asking colleagues for help.'
    },
    { 
      words: ['quick', 'fast', 'prompt', 'immediate'], 
      theme: 'Things get done quickly',
      explanation: 'Work processes are efficient and problems get solved fast. This happens when systems work properly, staff are well-trained, and there are enough people working during busy times.'
    }
  ];
  
  const negativeKeywords = [
    { 
      words: ['pressure', 'stress', 'overwork', 'burden', 'rush'], 
      theme: 'Too much work pressure',
      explanation: 'Staff feel stressed because there is too much work to do in the time given. This usually happens when there are not enough people working during busy times, or when tasks are not shared fairly among the team.'
    },
    { 
      words: ['late', 'delay', 'waiting', 'slow'], 
      theme: 'Things take too long',
      explanation: 'Processes are slow and people have to wait for approvals or systems to work. This creates frustration because staff cannot serve customers quickly or complete their tasks on time.'
    },
    { 
      words: ['partial', 'unfair', 'favorit', 'biased'], 
      theme: 'Some people get better treatment',
      explanation: 'Staff feel that some colleagues get special treatment while others are treated poorly. This happens when managers do not apply rules equally or show favoritism to certain people.'
    },
    { 
      words: ['break', 'rest', 'tired', 'exhausted'], 
      theme: 'Not enough rest time',
      explanation: 'Staff are not getting proper breaks or rest periods during their shifts. This makes people tired and affects their performance. It usually happens when shifts are poorly planned or too busy.'
    },
    { 
      words: ['confused', 'unclear', 'dont know', 'understand'], 
      theme: 'Information is not clear',
      explanation: 'Staff do not understand what they need to do or company policies are confusing. This happens when managers do not explain things properly or information is not shared clearly with the team.'
    },
    { 
      words: ['app', 'system', 'error', 'bug', 'crash'], 
      theme: 'Computer systems have problems',
      explanation: 'The apps and computer systems that staff use for work are not working properly. They crash, have errors, or are slow. This makes it difficult to serve customers and complete tasks efficiently.'
    },
    { 
      words: ['salary', 'pay', 'money', 'compensation'], 
      theme: 'Payment problems',
      explanation: 'There are issues with salary payments, bonuses, or other money matters. This could be delays in payment, wrong amounts, or confusion about compensation. This affects staff trust and motivation.'
    },
    { 
      words: ['rude', 'harsh', 'angry', 'shouting'], 
      theme: 'Manager is not friendly',
      explanation: 'The area manager speaks to staff in a rude or harsh way. This makes people feel uncomfortable and affects team morale. Good managers should be respectful and supportive, not aggressive or mean.'
    },
    { 
      words: ['no time', 'busy', 'cant', 'impossible'], 
      theme: 'Not enough time for tasks',
      explanation: 'Staff feel they do not have enough time to complete all their work properly. This happens when there are too many tasks, unrealistic deadlines, or not enough people to share the workload.'
    }
  ];

  // Count keyword occurrences
  const positiveDetails: Map<string, { count: number, explanation: string }> = new Map();
  const negativeDetails: Map<string, { count: number, explanation: string }> = new Map();
  
  positiveKeywords.forEach(({ words, theme, explanation }) => {
    let count = 0;
    allRemarks.forEach(remark => {
      if (words.some(word => remark.includes(word))) {
        count++;
      }
    });
    if (count > 0) {
      positives.set(theme, count);
      positiveDetails.set(theme, { count, explanation });
    }
  });
  
  negativeKeywords.forEach(({ words, theme, explanation }) => {
    let count = 0;
    allRemarks.forEach(remark => {
      if (words.some(word => remark.includes(word))) {
        count++;
      }
    });
    if (count > 0) {
      negatives.set(theme, count);
      negativeDetails.set(theme, { count, explanation });
    }
  });

  // Analyze scores by question with detailed root cause themes
  const questionThemes: { [key: string]: { 
    positive: { theme: string, explanation: string }, 
    negative: { theme: string, explanation: string } 
  } } = {
    q1: { 
      positive: { theme: 'Good staffing levels', explanation: 'There are enough people working during busy times so staff do not feel too much pressure. Managers plan the workforce well and make sure no one is overworked.' },
      negative: { theme: 'Not enough staff during busy times', explanation: 'There are too few people working when it gets busy, which puts pressure on everyone. This happens when managers do not plan properly for rush hours or busy periods.' }
    },
    q2: { 
      positive: { theme: 'Staff can make decisions', explanation: 'Employees are allowed to make important decisions when helping customers without always asking for permission. This makes work faster and more efficient.' },
      negative: { theme: 'Staff cannot decide things', explanation: 'Employees have to ask permission for too many small decisions, which slows down customer service. The approval process is too strict and takes too long.' }
    },
    q3: { 
      positive: { theme: 'Manager gives regular feedback', explanation: 'The area manager talks to staff regularly and gives helpful feedback about their work. This helps people improve and feel supported in their job.' },
      negative: { theme: 'Manager does not talk enough', explanation: 'The area manager does not meet with staff often enough or give feedback about their performance. People feel ignored and do not know how they are doing at work.' }
    },
    q4: { 
      positive: { theme: 'Everyone is treated fairly', explanation: 'All staff members get the same treatment and opportunities. The manager follows company rules equally for everyone and does not show favoritism.' },
      negative: { theme: 'Some people get better treatment', explanation: 'The manager treats some staff better than others, which is not fair. This creates jealousy and makes people feel unvalued or discriminated against.' }
    },
    q5: { 
      positive: { theme: 'Training programs work well', explanation: 'The training that staff receive is helpful and teaches them what they need to know for their job. The programs are well-organized and easy to understand.' },
      negative: { theme: 'Training programs have problems', explanation: 'The training is not helpful or well-organized. Staff do not learn what they need to know, or the training methods are confusing and ineffective.' }
    },
    q6: { 
      positive: { theme: 'Computer systems work well', explanation: 'The apps and computer systems that staff use are reliable and work properly. This helps people do their job efficiently without technical problems.' },
      negative: { theme: 'Computer systems keep breaking', explanation: 'The apps and computer systems have many problems like crashes, errors, or slow performance. This makes it difficult for staff to serve customers and complete their work.' }
    },
    q7: { 
      positive: { theme: 'Company information is clear', explanation: 'Staff understand company policies and procedures because information is shared clearly and regularly. Everyone knows what the rules are and how to follow them.' },
      negative: { theme: 'Company information is confusing', explanation: 'Staff do not understand company policies or procedures because information is not shared clearly. People are confused about what they should do or what the rules are.' }
    },
    q8: { 
      positive: { theme: 'Work schedules are good', explanation: 'Staff are happy with their work schedules because they are flexible and fair. Managers consider people\'s needs when making rosters and allow for work-life balance.' },
      negative: { theme: 'Work schedules are bad', explanation: 'Staff are unhappy with their schedules because they are too rigid or unfair. Managers do not consider people\'s personal needs when making rosters.' }
    },
    q9: { 
      positive: { theme: 'Team works well together', explanation: 'Staff members help each other and communicate well as a team. There is good cooperation and people feel comfortable working with their colleagues.' },
      negative: { theme: 'Team does not work well together', explanation: 'There are problems with teamwork and communication between staff members. People do not help each other or there are conflicts that affect the work environment.' }
    },
    q12: { 
      positive: { theme: 'Overall experience is very good', explanation: 'Staff have a positive experience working for the company because many things are working well together - good management, fair treatment, proper support, and a positive work environment.' },
      negative: { theme: 'Overall experience has many problems', explanation: 'Staff have a negative experience because there are multiple problems affecting their work - poor management, unfair treatment, lack of support, or a negative work environment.' }
    }
  };

  // Add themes based on scores
  Object.entries(scoresByQuestion).forEach(([qKey, scores]) => {
    if (scores.length === 0) return;
    
    const avgScore = scores.reduce((a, b) => a + b, 0) / scores.length;
    const theme = questionThemes[qKey];
    
    if (!theme) return;
    
    // High scores (>= 3.8) are very positive
    if (avgScore >= 3.8) {
      positives.set(theme.positive.theme, avgScore * 10);
      positiveDetails.set(theme.positive.theme, { count: avgScore * 10, explanation: theme.positive.explanation });
    } 
    // Low scores (<= 2.5) are negative
    else if (avgScore <= 2.5) {
      negatives.set(theme.negative.theme, (5 - avgScore) * 10);
      negativeDetails.set(theme.negative.theme, { count: (5 - avgScore) * 10, explanation: theme.negative.explanation });
    }
    // Medium-low scores (2.5-3.2) are mild concerns
    else if (avgScore <= 3.2) {
      negatives.set(theme.negative.theme, (4 - avgScore) * 5);
      negativeDetails.set(theme.negative.theme, { count: (4 - avgScore) * 5, explanation: theme.negative.explanation });
    }
  });

  // Get top 3 of each, sorted by frequency/score
  const topPositives = Array.from(positives.entries())
    .sort((a, b) => b[1] - a[1])
    .slice(0, 3)
    .map(([text]) => text);
  
  const topNegatives = Array.from(negatives.entries())
    .sort((a, b) => b[1] - a[1])
    .slice(0, 3)
    .map(([text]) => text);

  // Ensure we always have exactly 3 items with detailed root cause format
  const defaultPositives = [
    { theme: 'Work processes are stable', explanation: 'The daily work routines and processes are consistent and reliable. Staff know what to do and can deliver good service to customers regularly.' },
    { theme: 'Good work environment', explanation: 'People enjoy working here because there is a positive atmosphere. Staff feel comfortable and supported by their colleagues and managers.' }, 
    { theme: 'Basic training is adequate', explanation: 'Staff receive enough basic training to do their job properly. They understand the main tasks and company standards that are needed for their work.' }
  ];
  
  const defaultNegatives = [
    { theme: 'Need more feedback from staff', explanation: 'The company should ask staff for their opinions more often through surveys or meetings. This would help identify problems early and improve the workplace.' },
    { theme: 'Information sharing needs improvement', explanation: 'Communication between management and staff could be better. People need clearer and more regular updates about company news, changes, and expectations.' },
    { theme: 'More regular check-ins needed', explanation: 'Managers should meet with their staff more often to discuss performance and provide support. Regular one-on-one meetings would help solve problems faster.' }
  ];

  // Create detailed insights from the analysis
  const detailedPositivesArray = Array.from(positiveDetails.entries())
    .sort((a, b) => b[1].count - a[1].count)
    .slice(0, 3)
    .map(([theme, data]) => ({ summary: theme, explanation: data.explanation }));

  const detailedNegativesArray = Array.from(negativeDetails.entries())
    .sort((a, b) => b[1].count - a[1].count)
    .slice(0, 3)
    .map(([theme, data]) => ({ summary: theme, explanation: data.explanation }));

  // Ensure we have 3 items
  while (detailedPositivesArray.length < 3) {
    const defaultItem = defaultPositives[detailedPositivesArray.length];
    detailedPositivesArray.push({ summary: defaultItem.theme, explanation: defaultItem.explanation });
  }
  while (detailedNegativesArray.length < 3) {
    const defaultItem = defaultNegatives[detailedNegativesArray.length];
    detailedNegativesArray.push({ summary: defaultItem.theme, explanation: defaultItem.explanation });
  }

  return {
    positives: topPositives.length >= 3 ? topPositives : [...topPositives, ...defaultPositives.map(d => d.theme)].slice(0, 3),
    negatives: topNegatives.length >= 3 ? topNegatives : [...topNegatives, ...defaultNegatives.map(d => d.theme)].slice(0, 3),
    isAiGenerated: false,
    detailedInsights: {
      positives: detailedPositivesArray.slice(0, 3),
      negatives: detailedNegativesArray.slice(0, 3)
    }
  };
}

/**
 * Parses score from various formats
 */
function parseScore(value: any): number {
  if (!value) return 0;
  
  const str = String(value).toLowerCase().trim();
  
  // Map text responses to scores
  const scoreMap: { [key: string]: number } = {
    'never': 5,
    'at time': 4,
    'sometime': 3,
    'most of the time': 2,
    'every time': 1,
    'excellent': 5,
    'very good': 4,
    'good': 3,
    'average': 2,
    'poor': 1
  };
  
  // Check if it's a text response
  for (const [key, score] of Object.entries(scoreMap)) {
    if (str === key) {
      return score;
    }
  }
  
  // Try to parse as number
  const num = parseFloat(str);
  return isNaN(num) ? 0 : num;
}

/**
 * Cache for AI insights to avoid repeated API calls
 */
const insightsCache = new Map<string, { insights: InsightResult; timestamp: number }>();
const CACHE_DURATION = 30 * 60 * 1000; // 30 minutes

/**
 * Analyzes monthly submission data for detailed insights
 * @param monthName - Name of the month
 * @param submissions - Submissions for that specific month
 * @returns Promise with monthly insights
 */
export async function generateMonthlyInsights(monthName: string, submissions: any[]): Promise<InsightResult> {
  try {
    // If no submissions, return default
    if (submissions.length === 0) {
      return {
        positives: [`No data for ${monthName}`],
        negatives: [`No submissions recorded for ${monthName}`],
        isAiGenerated: false,
        detailedInsights: {
          positives: [{
            summary: `No data for ${monthName}`,
            explanation: `There were no survey submissions recorded for ${monthName}. This could mean staff were not surveyed during this period or responses were not collected properly.`
          }],
          negatives: [{
            summary: `No feedback collected`,
            explanation: `Without survey data, it is difficult to understand how staff felt during ${monthName}. Regular feedback collection helps identify both successes and areas that need improvement.`
          }]
        }
      };
    }

    // Calculate month-specific statistics
    const monthStats = calculateMonthStats(submissions);
    const remarks = extractRemarks(submissions);
    
    // Use AI analysis with month-specific context
    const insights = await analyzeMonthWithAI(monthName, submissions, monthStats, remarks);
    return insights;
    
  } catch (error) {
    console.error(`Error generating monthly insights for ${monthName}:`, error);
    return generateMonthlyFallback(monthName, submissions);
  }
}

/**
 * Calculates statistics for a specific month
 */
function calculateMonthStats(submissions: any[]) {
  const stats: { [key: string]: { scores: number[], avg: number } } = {};
  
  submissions.forEach(sub => {
    for (let i = 1; i <= 12; i++) {
      const qKey = `q${i}`;
      const score = parseScore(sub[qKey]);
      
      if (score > 0) {
        if (!stats[qKey]) {
          stats[qKey] = { scores: [], avg: 0 };
        }
        stats[qKey].scores.push(score);
      }
    }
  });
  
  // Calculate averages
  Object.keys(stats).forEach(qKey => {
    const scores = stats[qKey].scores;
    stats[qKey].avg = scores.length > 0 ? scores.reduce((a, b) => a + b, 0) / scores.length : 0;
  });
  
  return stats;
}

/**
 * Extracts remarks from submissions
 */
function extractRemarks(submissions: any[]): string[] {
  const remarks: string[] = [];
  
  submissions.forEach(sub => {
    for (let i = 1; i <= 12; i++) {
      const remarkKey = `q${i}_remarks`;
      const remark = sub[remarkKey];
      if (remark && String(remark).trim().length > 5) {
        remarks.push(String(remark).trim());
      }
    }
    
    if (sub.q11 && String(sub.q11).trim().length > 5) {
      remarks.push(String(sub.q11).trim());
    }
  });
  
  return remarks;
}

/**
 * Uses AI to analyze monthly data
 */
async function analyzeMonthWithAI(monthName: string, submissions: any[], monthStats: any, remarks: string[]): Promise<InsightResult> {
  const githubToken = process.env.GITHUB_TOKEN || ''; // Set your GitHub Personal Access Token in environment variables
  
  if (githubToken && githubToken.length > 0) {
    try {
      return await analyzeMonthWithGitHubModels(monthName, submissions, monthStats, remarks, githubToken);
    } catch (error) {
      console.warn(`GitHub Models API failed for ${monthName}, using fallback:`, error);
    }
  }
  
  return generateMonthlyFallback(monthName, submissions);
}

/**
 * AI analysis for monthly data
 */
async function analyzeMonthWithGitHubModels(
  monthName: string, 
  submissions: any[], 
  monthStats: any, 
  remarks: string[], 
  token: string
): Promise<InsightResult> {
  const endpoint = 'https://models.github.ai/inference/chat/completions';
  
  // Prepare month-specific analysis
  const monthSummary = Object.entries(monthStats).map(([q, data]: [string, any]) => {
    return `${q}: Average ${data.avg.toFixed(1)}/5 (${data.scores.length} responses)`;
  }).join('\n');
  
  const sampleRemarks = remarks.slice(0, 6).map(r => `"${r}"`).join(', ');
  
  const prompt = `Analyze survey data for ${monthName} and provide ROOT CAUSE ANALYSIS.

Month: ${monthName}
Total Submissions: ${submissions.length}

Question Averages:
${monthSummary}

Sample Employee Remarks:
${sampleRemarks}

Task: Identify what specifically happened in ${monthName} that caused positive and negative experiences.

Consider:
- What operational factors influenced this month's results?
- What management practices were working well or poorly?
- What system or process issues affected staff experience?
- What seasonal or business factors might have impacted performance?

Use SIMPLE ENGLISH that anyone can understand. Explain like talking to someone new to the company.

Format: Brief title + detailed explanation (max 150 chars for title)

Return ONLY valid JSON:
{
  "positives": [
    {
      "summary": "What went well in ${monthName}",
      "explanation": "Detailed explanation in simple terms about why this positive thing happened during this specific month"
    },
    {
      "summary": "Another positive factor",
      "explanation": "Clear explanation of what caused this good outcome in ${monthName}"
    },
    {
      "summary": "Third positive aspect", 
      "explanation": "Simple explanation of why this worked well during ${monthName}"
    }
  ],
  "negatives": [
    {
      "summary": "What caused problems in ${monthName}",
      "explanation": "Clear explanation in simple words about what went wrong and why it happened during this month"
    },
    {
      "summary": "Another issue in ${monthName}",
      "explanation": "Detailed but simple explanation of what caused this problem during this specific month"
    },
    {
      "summary": "Third concern",
      "explanation": "Easy-to-understand explanation of what led to this issue in ${monthName}"
    }
  ]
}`;

  const response = await fetch(endpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${token}`
    },
    body: JSON.stringify({
      model: 'gpt-4.1-mini',
      messages: [
        {
          role: 'system',
          content: `You are an expert workplace analyst who explains monthly performance patterns in SIMPLE, CLEAR language. Focus on what specifically happened during the given month that caused positive or negative experiences. Use everyday words and explain as if talking to someone new to the company. Always respond with valid JSON only.`
        },
        {
          role: 'user',
          content: prompt
        }
      ],
      temperature: 0.3,
      max_tokens: 800
    })
  });

  if (!response.ok) {
    throw new Error(`GitHub Models API error: ${response.status}`);
  }

  const data = await response.json();
  const content = data.choices?.[0]?.message?.content || '';
  
  // Parse JSON response
  const jsonMatch = content.match(/\{[\s\S]*\}/);
  if (jsonMatch) {
    try {
      const parsed = JSON.parse(jsonMatch[0]);
      
      const positives = (parsed.positives || []).slice(0, 3).map((item: any) => {
        if (typeof item === 'string') return item;
        return `${item.summary}: ${item.explanation}`;
      });
      
      const negatives = (parsed.negatives || []).slice(0, 3).map((item: any) => {
        if (typeof item === 'string') return item;
        return `${item.summary}: ${item.explanation}`;
      });
      
      return {
        positives,
        negatives,
        isAiGenerated: true,
        detailedInsights: {
          positives: (parsed.positives || []).slice(0, 3),
          negatives: (parsed.negatives || []).slice(0, 3)
        }
      };
    } catch (e) {
      console.error('Failed to parse monthly AI JSON:', e);
    }
  }
  
  throw new Error('Could not parse monthly AI response');
}

/**
 * Fallback analysis for monthly data
 */
function generateMonthlyFallback(monthName: string, submissions: any[]): InsightResult {
  const monthStats = calculateMonthStats(submissions);
  const remarks = extractRemarks(submissions);
  
  // Simple analysis based on scores and keywords
  const avgScores = Object.values(monthStats).map((stat: any) => stat.avg).filter(avg => avg > 0);
  const overallAvg = avgScores.length > 0 ? avgScores.reduce((a, b) => a + b, 0) / avgScores.length : 3.0;
  
  let positives: Array<{ summary: string, explanation: string }> = [];
  let negatives: Array<{ summary: string, explanation: string }> = [];
  
  // Score-based analysis
  if (overallAvg >= 3.8) {
    positives.push({
      summary: `Strong performance in ${monthName}`,
      explanation: `Staff gave high ratings across most areas during ${monthName}. This suggests that management practices, work conditions, and support systems were working well during this period.`
    });
  } else if (overallAvg >= 3.2) {
    positives.push({
      summary: `Decent performance in ${monthName}`,
      explanation: `Most staff were reasonably satisfied during ${monthName}. While there were some areas for improvement, the overall experience was positive for most employees.`
    });
  }
  
  if (overallAvg <= 2.5) {
    negatives.push({
      summary: `Multiple concerns in ${monthName}`,
      explanation: `Staff ratings were low across several areas during ${monthName}. This indicates there were significant challenges with work conditions, management support, or operational issues during this period.`
    });
  } else if (overallAvg <= 3.2) {
    negatives.push({
      summary: `Some areas need attention in ${monthName}`,
      explanation: `While not critically low, some aspects of the work experience during ${monthName} could be improved. Staff feedback suggests there were moderate concerns that should be addressed.`
    });
  }
  
  // Keyword analysis from remarks
  const allRemarksText = remarks.join(' ').toLowerCase();
  
  if (allRemarksText.includes('good') || allRemarksText.includes('great') || allRemarksText.includes('happy')) {
    positives.push({
      summary: `Positive feedback during ${monthName}`,
      explanation: `Staff specifically mentioned positive experiences in their comments during ${monthName}. This indicates good management support and work environment during this period.`
    });
  }
  
  if (allRemarksText.includes('problem') || allRemarksText.includes('issue') || allRemarksText.includes('difficult')) {
    negatives.push({
      summary: `Issues reported in ${monthName}`,
      explanation: `Staff mentioned specific problems or difficulties in their feedback during ${monthName}. These concerns should be investigated and addressed to improve future experiences.`
    });
  }
  
  // Ensure we have at least one item in each category
  if (positives.length === 0) {
    positives.push({
      summary: `Regular operations in ${monthName}`,
      explanation: `Work continued normally during ${monthName} with staff completing their daily tasks. While there may not have been outstanding successes, basic operations remained stable.`
    });
  }
  
  if (negatives.length === 0) {
    negatives.push({
      summary: `Limited feedback for ${monthName}`,
      explanation: `There was not enough detailed feedback to identify specific concerns during ${monthName}. More regular check-ins with staff could help identify areas for improvement.`
    });
  }
  
  // Fill to 3 items
  while (positives.length < 3) {
    positives.push({
      summary: `Standard performance maintained`,
      explanation: `Basic work standards and procedures were followed during ${monthName}, ensuring consistent service delivery and operational continuity.`
    });
  }
  
  while (negatives.length < 3) {
    negatives.push({
      summary: `Monitor for improvements`,
      explanation: `Regular monitoring and staff feedback collection during periods like ${monthName} helps identify opportunities for enhancing the work experience.`
    });
  }
  
  return {
    positives: positives.slice(0, 3).map(p => p.summary),
    negatives: negatives.slice(0, 3).map(n => n.summary),
    isAiGenerated: false,
    detailedInsights: {
      positives: positives.slice(0, 3),
      negatives: negatives.slice(0, 3)
    }
  };
}

/**
 * Get insights with caching
 */
export async function getCachedAMInsights(amId: string, submissions: any[]): Promise<InsightResult> {
  const cacheKey = `${amId}_${submissions.length}`;
  const cached = insightsCache.get(cacheKey);
  
  // Check if cache is valid
  if (cached && Date.now() - cached.timestamp < CACHE_DURATION) {
    console.log('✅ Using cached insights for AM:', amId);
    return cached.insights;
  }
  
  // Generate new insights
  console.log('🔄 Generating new insights for AM:', amId);
  const insights = await generateAMInsights(submissions);
  
  // Cache the results
  insightsCache.set(cacheKey, {
    insights,
    timestamp: Date.now()
  });
  
  return insights;
}
