// Static AM Operations test data for development
// Updated with correct region mapping and realistic BSC% values based on Latest_Mapping.json

import { AMOperationsSubmission } from './dataService';

export const STATIC_AM_OPERATIONS_DATA: AMOperationsSubmission[] = [
  // South Region stores - Based on Latest_Mapping.json
  {
    submissionTime: '2024-10-01T10:30:00Z',
    hrName: 'Sarah Johnson',
    hrId: 'HR001',
    amName: 'Michael Chen',
    amId: 'AM001',
    trainerName: 'Priya Sharma',
    trainerId: 'T001',
    storeName: 'Koramangala',
    storeId: 'S001',
    region: 'South',
    bscAchievement: '87%',
    peopleOnShift: '8',
    manpowerFulfilment: 'High',
    cafeType: 'PREMIUM',
    storeType: 'Mall',
    concept: 'Experience',
    totalScore: '87',
    maxScore: '100',
    percentageScore: '87',
    CG_1: '4', CG_2: '5', CG_3: '4', CG_4: '5', CG_5: '4',
    OTA_1: '5', OTA_2: '4', OTA_3: '5', OTA_4: '4', OTA_5: '5',
    SOP_1: '4', SOP_2: '5', SOP_3: '4', SOP_4: '4', SOP_5: '5'
  },
  {
    submissionTime: '2024-10-02T14:15:00Z',
    hrName: 'Sarah Johnson',
    hrId: 'HR001',
    amName: 'Michael Chen',
    amId: 'AM001',
    trainerName: 'Priya Sharma',
    trainerId: 'T001',
    storeName: 'UB City',
    storeId: 'S007',
    region: 'South',
    bscAchievement: '92%',
    peopleOnShift: '7',
    manpowerFulfilment: 'Med',
    cafeType: 'PREMIUM+',
    storeType: 'Highstreet',
    concept: 'Premium',
    totalScore: '92',
    maxScore: '100',
    percentageScore: '92',
    CG_1: '5', CG_2: '5', CG_3: '4', CG_4: '5', CG_5: '5',
    OTA_1: '5', OTA_2: '5', OTA_3: '5', OTA_4: '4', OTA_5: '5',
    SOP_1: '5', SOP_2: '5', SOP_3: '4', SOP_4: '5', SOP_5: '4'
  },
  {
    submissionTime: '2024-10-03T09:20:00Z',
    hrName: 'Sarah Johnson',
    hrId: 'HR001',
    amName: 'Michael Chen',
    amId: 'AM001',
    trainerName: 'Rajesh Kumar',
    trainerId: 'T002',
    storeName: 'HSR-1',
    storeId: 'S003',
    region: 'South',
    bscAchievement: '85%',
    peopleOnShift: '6',
    manpowerFulfilment: 'Med',
    cafeType: 'REGULAR',
    storeType: 'Corporate',
    concept: 'Classic',
    totalScore: '85',
    maxScore: '100',
    percentageScore: '85',
    CG_1: '4', CG_2: '4', CG_3: '5', CG_4: '4', CG_5: '4',
    OTA_1: '4', OTA_2: '5', OTA_3: '4', OTA_4: '5', OTA_5: '4',
    SOP_1: '4', SOP_2: '4', SOP_3: '5', SOP_4: '4', SOP_5: '5'
  },

  // North Region stores - Based on Latest_Mapping.json
  {
    submissionTime: '2024-10-04T11:45:00Z',
    hrName: 'Rohit Patel',
    hrId: 'HR002',
    amName: 'Emily Watson',
    amId: 'AM002',
    trainerName: 'Anjali Verma',
    trainerId: 'T003',
    storeName: 'Deer Park',
    storeId: 'S024',
    region: 'North',
    bscAchievement: '79%',
    peopleOnShift: '9',
    manpowerFulfilment: 'High',
    cafeType: 'EXPRESS',
    storeType: 'Franchise',
    concept: 'Express',
    totalScore: '79',
    maxScore: '100',
    percentageScore: '79',
    CG_1: '3', CG_2: '4', CG_3: '4', CG_4: '4', CG_5: '3',
    OTA_1: '4', OTA_2: '4', OTA_3: '3', OTA_4: '4', OTA_5: '4',
    SOP_1: '3', SOP_2: '4', SOP_3: '4', SOP_4: '3', SOP_5: '4'
  },
  {
    submissionTime: '2024-10-05T13:30:00Z',
    hrName: 'Rohit Patel',
    hrId: 'HR002',
    amName: 'Emily Watson',
    amId: 'AM002',
    trainerName: 'Anjali Verma',
    trainerId: 'T003',
    storeName: 'Khan Market',
    storeId: 'S037',
    region: 'North',
    bscAchievement: '83%',
    peopleOnShift: '7',
    manpowerFulfilment: 'Med',
    cafeType: 'PREMIUM',
    storeType: 'Mall',
    concept: 'Experience',
    totalScore: '83',
    maxScore: '100',
    percentageScore: '83',
    CG_1: '4', CG_2: '4', CG_3: '4', CG_4: '4', CG_5: '4',
    OTA_1: '4', OTA_2: '4', OTA_3: '4', OTA_4: '4', OTA_5: '4',
    SOP_1: '4', SOP_2: '4', SOP_3: '4', SOP_4: '4', SOP_5: '3'
  },
  {
    submissionTime: '2024-10-06T16:10:00Z',
    hrName: 'Rohit Patel',
    hrId: 'HR002',
    amName: 'Emily Watson',
    amId: 'AM002',
    trainerName: 'Vikram Singh',
    trainerId: 'T004',
    storeName: 'Connaught Place E Block',
    storeId: 'S049',
    region: 'North',
    bscAchievement: '88%',
    peopleOnShift: '8',
    manpowerFulfilment: 'High',
    cafeType: 'PREMIUM+',
    storeType: 'Highstreet',
    concept: 'Premium',
    totalScore: '88',
    maxScore: '100',
    percentageScore: '88',
    CG_1: '4', CG_2: '5', CG_3: '4', CG_4: '4', CG_5: '5',
    OTA_1: '5', OTA_2: '4', OTA_3: '5', OTA_4: '4', OTA_5: '4',
    SOP_1: '4', SOP_2: '5', SOP_3: '4', SOP_4: '4', SOP_5: '4'
  },

  // West Region stores - Based on Latest_Mapping.json
  {
    submissionTime: '2024-10-07T08:45:00Z',
    hrName: 'Kavya Sharma',
    hrId: 'HR003',
    amName: 'Robert Taylor',
    amId: 'AM003',
    trainerName: 'Meera Joshi',
    trainerId: 'T005',
    storeName: 'Kemps Corner',
    storeId: 'S043',
    region: 'West',
    bscAchievement: '91%',
    peopleOnShift: '10',
    manpowerFulfilment: 'High',
    cafeType: 'PREMIUM+',
    storeType: 'Corporate',
    concept: 'Experience',
    totalScore: '91',
    maxScore: '100',
    percentageScore: '91',
    CG_1: '5', CG_2: '5', CG_3: '4', CG_4: '5', CG_5: '4',
    OTA_1: '5', OTA_2: '5', OTA_3: '4', OTA_4: '5', OTA_5: '5',
    SOP_1: '4', SOP_2: '5', SOP_3: '5', SOP_4: '4', SOP_5: '5'
  },
  {
    submissionTime: '2024-10-08T12:20:00Z',
    hrName: 'Kavya Sharma',
    hrId: 'HR003',
    amName: 'Robert Taylor',
    amId: 'AM003',
    trainerName: 'Arjun Nair',
    trainerId: 'T006',
    storeName: 'Kalyani Nagar - Pune',
    storeId: 'S048',
    region: 'West',
    bscAchievement: '76%',
    peopleOnShift: '5',
    manpowerFulfilment: 'Low',
    cafeType: 'REGULAR',
    storeType: 'Franchise',
    concept: 'Classic',
    totalScore: '76',
    maxScore: '100',
    percentageScore: '76',
    CG_1: '3', CG_2: '4', CG_3: '3', CG_4: '4', CG_5: '3',
    OTA_1: '4', OTA_2: '3', OTA_3: '4', OTA_4: '3', OTA_5: '4',
    SOP_1: '3', SOP_2: '4', SOP_3: '3', SOP_4: '4', SOP_5: '3'
  },
  {
    submissionTime: '2024-10-09T15:35:00Z',
    hrName: 'Kavya Sharma',
    hrId: 'HR003',
    amName: 'Robert Taylor',
    amId: 'AM003',
    trainerName: 'Meera Joshi',
    trainerId: 'T005',
    storeName: 'Banjara Hills Road no.12',
    storeId: 'S084',
    region: 'West',
    bscAchievement: '89%',
    peopleOnShift: '8',
    manpowerFulfilment: 'High',
    cafeType: 'PREMIUM',
    storeType: 'Mall',
    concept: 'Premium',
    totalScore: '89',
    maxScore: '100',
    percentageScore: '89',
    CG_1: '4', CG_2: '5', CG_3: '4', CG_4: '5', CG_5: '4',
    OTA_1: '5', OTA_2: '4', OTA_3: '5', OTA_4: '4', OTA_5: '5',
    SOP_1: '4', SOP_2: '5', SOP_3: '4', SOP_4: '4', SOP_5: '5'
  }
];

// Regional performance summary based on correct mapping:
// South: 88% average BSC (3 stores: S001, S007, S003)
// North: 83% average BSC (3 stores: S024, S037, S049)  
// West: 85% average BSC (3 stores: S043, S048, S084)